#📌 Урок: Работа с файлами
##📖 Теоретический минимум

Текстовые файлы (.txt) - простые файлы с неструктурированным текстом

CSV (Comma-Separated Values) - табличные данные с разделителями

Excel (.xlsx, .xls) - электронные таблицы с расширенными возможностями

JSON - структурированные данные в формате ключ-значение

Бинарные файлы - изображения, PDF и другие нетекстовые форматы

# 🔹 Основные операции с файлами
Открытие/закрытие файла

Чтение данных

Запись данных

Обработка больших файлов


#📖 Материалы

https://vkvideo.ru/video-194554202_456239677

https://vkvideo.ru/video-194554202_456239682









# 🏆 Задания

## 1️⃣ Работа с текстовыми файлами
**Задача:**
 Создать текстовый файл, записать в него str данные и прочитать обратно

	•	open("example.txt", "w") — открывает файл в режиме записи (перезапишет, если уже есть).
	•	open("example.txt", "r") — открывает файл в режиме чтения.
	•	with ... as ...: — автоматически закрывает файл после завершения блока.
	•	encoding="utf-8" — чтобы кириллица и другие символы корректно обрабатывались.

In [1]:
text = "абоба"

# запись
with open("task_9_1.txt", "w") as file:
    file.write(text)

# чтение
with open("task_9_1.txt", "r") as file:
    my_file = file.read()

print(my_file)

абоба



## 2️⃣ Работа с CSV файлами

**Задача:**

Создать CSV файл с табличными данными, записать и прочитать его



	•	csv.writer(file) — объект для записи строк.
	•	writerows(data) — записывает сразу весь список строк.
	•	csv.reader(file) — позволяет читать строки построчно как списки.
	•	newline="" — важно при записи, чтобы не было пустых строк между записями в Windows.

In [2]:
import csv

data = [
    ["Имя", "Место", "Время,сек"],
    ["Леха", 1, 15],
    ["Вова", 2, 15.5],
    ["Настя", 3, 17]
]

# запись
with open("task_9_2.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerows(data)

# чтение
with open("task_9_2.csv", "r", encoding="utf-8") as file:
    reader = csv.reader(file)
    for i in reader:
        print(i)

['Имя', 'Место', 'Время,сек']
['Леха', '1', '15']
['Вова', '2', '15.5']
['Настя', '3', '17']


## 3️⃣  Работа с Excel файлами
**Задача:** Создать Excel файл и прочитать данные из него

Используйте библиотеку pandas

---



In [3]:
import pandas as pd

data = {
    "Имя": ["Леха", "Настя", "Вова"],
    "Место": [1, 2, 3],
    "Время": [13, 13.1, 20]
}

df = pd.DataFrame(data)

# запись
df.to_excel("task_9_3.xlsx", index=False)

# чтение
df_read = pd.read_excel("task_9_3.xlsx")

df_read

Имя  Место  Время
0   Леха      1   13.0
1  Настя      2   13.1
2   Вова      3   20.0


## 4️⃣  Чтение больших файлов по частям


**Задача:** Обработать файл построчно без загрузки в память целиком

Реализуйте чанки самостоятельно или воспользуйтесь chunk из pandas

---




In [6]:
import pandas as pd

chunk_size = 10
filename = 'task_9_4.csv'

for i in pd.read_csv(filename, chunksize=chunk_size):
    print(i)

         id                name      segment           state             city
0  CG-12520         Claire Gute     Consumer        Kentucky        Henderson
1  DV-13045     Darrin Van Huff    Corporate      California      Los Angeles
2  SO-20335      Sean O'Donnell     Consumer         Florida  Fort Lauderdale
3  BH-11710     Brosina Hoffman     Consumer      California      Los Angeles
4  AA-10480        Andrew Allen     Consumer  North Carolina          Concord
5  IM-15070        Irene Maddox     Consumer      Washington          Seattle
6  HP-14815       Harold Pawlan  Home Office           Texas       Fort Worth
7  PK-19075           Pete Kriz     Consumer       Wisconsin          Madison
8  AG-10270     Alejandro Grove     Consumer            Utah      West Jordan
9  ZD-21925  Zuschuss Donatelli     Consumer      California    San Francisco
          id             name      segment         state          city
10  KB-16585        Ken Black    Corporate      Nebraska       Fremont



## 5️⃣ Чтение JPEG файла
**Задача:**

Создайте изображение 21х21 пиксель в формате JPEG

Прочитайте JPEG файл в бинарном режиме

Выведете прочитанный файл как массив интенсивности пикселей

---


In [12]:
from PIL import Image
import numpy as np

# создание картинки
for_img = np.random.randint(0, 255, (21, 21, 3), dtype=np.uint8)
img = Image.fromarray(for_img)
img.save("image.jpeg", format="JPEG")

# чтение файла в бинарном режиме
with open("image.jpeg", "rb") as file:
    binary_data = file.read()

# чтение как массива интенсивности пикселей
img_loaded = Image.open("image.jpeg")
pixels = np.array(img_loaded)
print(pixels)

[[[ 15 111  39]
  [119 212 141]
  [ 39 126  57]
  ...
  [166 116 117]
  [139  66  49]
  [210 110  74]]

 [[108 172 120]
  [ 98 157 113]
  [ 56 100  73]
  ...
  [ 88  49  52]
  [190 133 126]
  [183 110  91]]

 [[103 106  97]
  [108  96 108]
  [ 91  50 106]
  ...
  [223 206 214]
  [199 179 191]
  [ 93  72  89]]

 ...

 [[ 96  65 203]
  [ 83  57 156]
  [114  95 114]
  ...
  [134 111 121]
  [218 202 203]
  [ 99  90  83]]

 [[100 101 228]
  [ 94  98 185]
  [150 159 168]
  ...
  [102  94 115]
  [114 118 127]
  [115 129 129]]

 [[134 173 250]
  [  0  41  81]
  [ 46  90  55]
  ...
  [ 26  76  73]
  [143 210 193]
  [ 44 124  97]]]
